# Generated by Django 2.1.1 on 2018-09-23 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='general',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='general',
            old_name='modified_at',
            new_name='updated_at',
        ),
    ]
