# Generated by Django 2.1.1 on 2018-10-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0005_gallery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(help_text='resolution 200x300px', upload_to='gallery'),
        ),
    ]
