# Generated by Django 2.1.1 on 2018-10-07 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0006_auto_20181007_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
