# Generated by Django 2.1.1 on 2018-10-07 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0007_auto_20181007_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='user_created',
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
