# Generated by Django 2.1.1 on 2018-10-09 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0011_gallery_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerycategory',
            old_name='category_name',
            new_name='category',
        ),
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='company_profile.GalleryCategory'),
        ),
    ]
