# Generated by Django 2.1.1 on 2018-10-09 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0012_auto_20181009_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerycategory',
            name='Slug',
            field=models.SlugField(blank=True, max_length=128, null=True),
        ),
    ]
