# Generated by Django 2.1.1 on 2018-10-09 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0013_gallerycategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='company_profile.GalleryCategory'),
        ),
    ]
