# Generated by Django 2.1.1 on 2018-10-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0014_auto_20181009_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, max_length=120, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='gallerycategory',
            name='Slug',
            field=models.SlugField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
