# Generated by Django 2.1.2 on 2018-10-10 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0016_howtoorder_product_productcategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallerycategory',
            old_name='Slug',
            new_name='slug',
        ),
    ]
