# Generated by Django 2.1.2 on 2018-10-13 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0024_auto_20181013_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quality',
            options={'verbose_name': 'Kualitas Kaos', 'verbose_name_plural': 'Kualitas Kaos'},
        ),
    ]
