# Generated by Django 2.1.2 on 2018-10-13 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0025_auto_20181013_1521'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Tentang Kami', 'verbose_name_plural': 'Tentang Kami'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Hubungi Kami', 'verbose_name_plural': 'Hubungi Kami'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Galeri', 'verbose_name_plural': 'Galeri'},
        ),
        migrations.AlterModelOptions(
            name='gallerycategory',
            options={'verbose_name': 'Galeri Kategori', 'verbose_name_plural': 'Galeri Kategori'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Produk', 'verbose_name_plural': 'Produk'},
        ),
        migrations.AlterModelOptions(
            name='productcategory',
            options={'verbose_name': 'Produk Kategori', 'verbose_name_plural': 'Produk Kategori'},
        ),
    ]
